<a href="https://colab.research.google.com/github/ellieleut/introToML/blob/main/pythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Python as a calculator
# Define variables
Conversion_factor = 5/9
TempTodayinF = 47
FreezingPointF = 32
TempTodayinC = Conversion_factor*(TempTodayinF - FreezingPointF)
TempTodayinC


8.333333333333334

In [ ]:
a = 2
type(a)

int

In [ ]:
b = 4e-7
type(b)

float

In [ ]:
2.1 + 3.2

5.300000000000001

In [ ]:
# Very very close to zero because of finite precision
5.3 - (2.1 + 3.2)

-8.881784197001252e-16

In [ ]:
5 % 2

1

In [ ]:
# operations on strings
'Hello, ' + 'world.'
'Hello, world.' * 3

'Hello, world.Hello, world.Hello, world.'

In [ ]:
type(True)

bool

In [ ]:
False == 0

True

In [ ]:
True + False

1

In [ ]:
type(True + False)

int

In [ ]:
True and True

True

In [ ]:
not(False and True)

True

In [ ]:
7 == 7 or 7.6 == 9.1

True

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_list[3] = 'four'

my_list

[1, 2, 3, 'four', 5, 6, 7, 8, 9, 10]

In [ ]:
numbers = [1, 2 , 3, 4, 5, 6, 7, 8, 9, 10]
print(numbers)
print(numbers[2:5])
print(numbers[1:10:2])
print(numbers[3:9])
print(numbers[1::2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5]
[2, 4, 6, 8, 10]
[4, 5, 6, 7, 8, 9]
[2, 4, 6, 8, 10]


In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_list[3] = 'four'

my_list

[1, 2, 3, 'four', 5, 6, 7, 8, 9, 10]

In [ ]:
a = 6
print(id(a))

11654536


In [ ]:
my_tuple = (0,)

not_a_tuple = (0) # this is just the number 0 (normal use of parantheses)

type(my_tuple), type(not_a_tuple)

(tuple, int)

In [ ]:
my_tuple = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Reverse
my_tuple[::-1]

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

In [ ]:
for i in range(10):
    print(i, end='  ')

0  1  2  3  4  5  6  7  8  9  

In [ ]:
n = 0
while n<5:
  print("Executing while loop")
  print(n)
  n = n+1

print("Finished while loop")
print(n)

Executing while loop
0
Executing while loop
1
Executing while loop
2
Executing while loop
3
Executing while loop
4
Finished while loop
5


In [ ]:
#purchasePrice = float(input("Price at which you have purchased a stock: "))
#currentPrice = float(input("current price of the stock: "))

purchasePrice = 25.55
currentPrice = 23

if currentPrice < purchasePrice:
  print("Not a good idea to sell your stock now.")
  print("You will lose", purchasePrice-currentPrice, "dollar per stock")
elif currentPrice == purchasePrice:
  print("Still not a good idea to sell your stock now.")
else:
   print("Sell your stock now.")
   print("You will make", currentPrice-purchasePrice, "dollar per stock")

Not a good idea to sell your stock now.
You will lose 2.5500000000000007 dollar per stock


In [ ]:
# print the squared numbers for the numbers in a list.
numbers = list(range(10));
for num in numbers:
    squared = num**2
    print(num, "sqaured is", squared )

0 sqaured is 0
1 sqaured is 1
2 sqaured is 4
3 sqaured is 9
4 sqaured is 16
5 sqaured is 25
6 sqaured is 36
7 sqaured is 49
8 sqaured is 64
9 sqaured is 81


In [ ]:
for i in range(10):
    print(i, end='  ')
print()

# Print numbers 2 through 9
for i in range(2, 10):
    print(i, end='     ')

# Print a newline
print()

# Print even numbers, 2 through 9
for i in range(2, 10, 2):
    print(i, end='     ')

0  1  2  3  4  5  6  7  8  9  
2     3     4     5     6     7     8     9     
2     4     6     8     

In [ ]:
n = 0

while True: #execute indefinitely
  print('Executing while loop')
  n = n + 1
  if n == 5: #stop loop if n reaches to 5
        break
print("Finished while loop")

Executing while loop
Executing while loop
Executing while loop
Executing while loop
Executing while loop
Finished while loop


In [ ]:
def ratio(x, y):
    """The ratio of `x` to `y`."""
    return x / y

In [ ]:
# Write a function definition named sum_all that takes in sequence of numbers and returns all the numbers added together.
def sum_all(numbers):
    total = 0
    for num in numbers:
        total += num
    return total

sum_all([1, 2, 3])

6

In [3]:
def factorial(n):
  "compute the factorial of a number n"
  result = 1
  for i in range(1,n+1):
    result = result*i
  return result
factorial(5)

120

In [6]:
# difference between method and function, let's sort a list
numbers = [4, 9, 7, 0, 9]

sorted_num = sorted(numbers)
print (numbers)
print(sorted_num)

# numbers.sort() by itself doesnt print
numbers.sort()
print(numbers)

[4, 9, 7, 0, 9]
[0, 4, 7, 9, 9]
[0, 4, 7, 9, 9]


In [7]:
my_list = [0, 1, 2, 3, 4]

my_list.append(5)

my_list

[0, 1, 2, 3, 4, 5]

In [10]:
# use a list nums = [10, 20, 30, 40], append 50, use pop to remove the last element and print it, use reverse to reverse the list, then print the final list
nums = [10, 20, 30, 40]

nums.append(50)
print("List after appending 50:", nums)

popped_element = nums.pop()
print("List after popping:", nums)

nums.reverse()
print("Final list after reversing:", nums)

List after appending 50: [10, 20, 30, 40, 50]
List after popping: [10, 20, 30, 40]
Final list after reversing: [40, 30, 20, 10]


In [15]:
# Create an array of evenly spaced values based on fixed step size. Use np.arange(start, stop, step). Note, stop values is excluded
# similar to range function for list. Syntax:  range(start, stop, step)
import numpy as np
np.arange(0, 10, 1)
# Create an array with evenly spaced values based on a fixed number of points. Use np.linspace(start, stop, num).  Note, stop values is included
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
# slicing Numpy arrays
# Make an array of random numbers between zero and one
rand_ar = np.random.rand(10)
print(rand_ar)

[0.89548426 0.07337948 0.46254399 0.2243919  0.50176049 0.88755142
 0.54838173 0.96611173 0.55723951 0.97967257]


In [21]:
# print the first 10 elements
rand_ar[0:10:1]

array([0.66662476, 0.02629254, 0.00927845, 0.93681172, 0.80103253,
       0.87229027, 0.21596818, 0.57993441, 0.45324775, 0.79148366])

In [23]:
# Every 5th element, starting at index 3
rand_ar[3::5]

array([0.93681172, 0.45324775])

In [22]:
# Entries 10 to 20
rand_ar[10:20]

array([], dtype=float64)

NameError: name 'rand_array2d' is not defined